exports.seed = async function (knex) {
	// Deletes ALL existing entries
	await knex('words').insert([
		{ category: 3, word: 'ごきげんよう' },
		{ category: 3, word: 'やほですわ' },
		{ category: 3, word: 'おつかれさま' },
		{ category: 3, word: 'おはようです' },
		{ category: 3, word: 'ひさしぶりね' },
		{ category: 3, word: '会えてうれし' },
		{ category: 3, word: 'ありがとです' },
		{ category: 3, word: '今日もかわよ' },
		{ category: 3, word: '元気だった？' },
		{ category: 3, word: 'めちゃ良きね' },
		{ category: 3, word: '超ありがとう' },
		{ category: 3, word: '尊み感じます' },
		{ category: 3, word: '推し最高です' },
		{ category: 3, word: 'きゅんですわ' },
		{ category: 3, word: 'とても神です' },
		{ category: 3, word: 'おつですわね' },
		{ category: 3, word: 'ぴえんですわ' },
		{ category: 3, word: '優勝ですわよ' },
		{ category: 3, word: 'しんどかわい' },
		{ category: 3, word: 'はい感謝しか' },
		{ category: 3, word: 'テンあがる' },
		{ category: 3, word: '好きすぎです' },
		{ category: 3, word: 'マジ助かるわ' },
		{ category: 3, word: 'それなですわ' },
		{ category: 3, word: '本当尊いの' },
		{ category: 3, word: '映えてますね' },
		{ category: 3, word: 'よきでしたわ' },
		{ category: 3, word: '推せるわねぇ' },
		{ category: 3, word: '神対応です' },
		{ category: 3, word: 'わかりみ深い' },
	]);
};
