exports.seed = async function (knex) {
	// Deletes ALL existing entries
	await knex('words').insert([
		{ category: 3, word: 'ごきげんよう' },
		{ category: 3, word: 'やほですわ' },
		{ category: 3, word: 'メンブレですの' },
		{ category: 3, word: 'おはようです' },
		{ category: 3, word: 'まじですの' },
		{ category: 3, word: 'ガチですわ！' },
		{ category: 3, word: 'おこですわ' },
		{ category: 3, word: 'ゆめかわですの' },
		{ category: 3, word: '草生えましてよ' },
		{ category: 3, word: 'ひよってますわ' },
		{ category: 3, word: 'つらたんですの' },
		{ category: 3, word: '安定すぎましてよ' },
		{ category: 3, word: 'あざとすぎますわ' },
		{ category: 3, word: 'きゅんですわ' },
		{ category: 3, word: 'チルですわ' },
		{ category: 3, word: 'おつですわね' },
		{ category: 3, word: 'ぴえんですわ' },
		{ category: 3, word: '優勝ですわよ' },
		{ category: 3, word: 'うけましてよ' },
		{ category: 3, word: 'キュルルンですわ' },
		{ category: 3, word: 'おだまりあそばせ' },
		{ category: 3, word: '激アツですわ' },
		{ category: 3, word: 'エモすぎますの' },
		{ category: 3, word: 'それなですわ' },
		{ category: 3, word: 'はにゃ？ですわ' },
		{ category: 3, word: 'ヤバみしかなくてよ' },
		{ category: 3, word: 'よきでしたわ' },
		{ category: 3, word: 'ばぶみ感じますわ' },
		{ category: 3, word: 'やばたにえんですわ' },
		{ category: 3, word: 'ドン引きですわね' },
	]);
};
