exports.seed = async function (knex) {
	// Deletes ALL existing entries
	await knex('words').insert([
		{ category: 3, word: 'ソウル' },
		{ category: 3, word: 'ボス戦' },
		{ category: 3, word: 'ステータス' },
		{ category: 3, word: 'レベルアップ' },
		{ category: 3, word: '武器強化' },
		{ category: 3, word: 'ダークソウル' },
		{ category: 3, word: 'デモンズ' },
		{ category: 3, word: '回復薬' },
		{ category: 3, word: '回避行動' },
		{ category: 3, word: 'ガード' },
		{ category: 3, word: 'パリィ' },
		{ category: 3, word: 'スタミナ' },
		{ category: 3, word: 'マルチプレイ' },
		{ category: 3, word: 'オンライン侵入' },
		{ category: 3, word: 'ソウル取得' },
		{ category: 3, word: 'ボス攻略' },
		{ category: 3, word: 'トロフィー' },
		{ category: 3, word: 'ドロップ率' },
		{ category: 3, word: '武器派生' },
		{ category: 3, word: '魔法攻撃' },
		{ category: 3, word: '装備強化' },
		{ category: 3, word: '難易度高め' },
		{ category: 3, word: 'ステルス' },
		{ category: 3, word: '協力プレイ' },
		{ category: 3, word: '装備重量' },
		{ category: 3, word: 'ロールプレイ' },
		{ category: 3, word: 'ボスムーブ' },
		{ category: 3, word: 'ダッシュ' },
		{ category: 3, word: 'ボス詰み' },
		{ category: 3, word: 'ファストトラベル' },
	]);
};
